### ISSUE TITLE
Doesn't work in TypeScript

### ISSUE THREAD

**Issue by JVMartin** [niieani/hashids.js#158]
Currently doesn't work in TypeScript, because it doesn't use valid export module syntax.

Example code:

```typescript
import Hashids from 'hashids';

const hashids = new Hashids();

console.log(hashids.encode(1));
```

Output of `ts`:
```text
export { Hashids as default };
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/jacob/code/hashids-is-broken/src/main.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module.m._compile (/home/jacob/code/hashids-is-broken/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
```

Offending line in current `master` is not valid:
https://github.com/niieani/hashids.js/blob/7b5d1577bfdd9d6e291caefce51ad2ab96ea2d26/esm/index.js#L277

Here's an example repository you can use to prove the error:
https://github.com/JVMartin/hashids-is-broken

Use it like so:
```
git clone https://github.com/JVMartin/hashids-is-broken.git
cd hashids-is-broken
npm install
npm run start
```

**Comment by JVMartin** [comment]
The only way you can get it to work is if you import from `dist` folder and ts-ignore it (yuck!), like so:

```typescript
// @ts-ignore
import Hashids from 'hashids/dist/hashids';
```

**Comment by niieani** [comment]
You're running a Node project without ESM, so you need to import from `hashids/cjs`.
I've cleared that up in the README.

**Comment by asktree** [comment]
I was getting this issue on 2.2.1 with node 10, had to use hashids/cjs.

**Comment by andidev** [comment]
same here

**Comment by heyask** [comment]
still not working

**Comment by niieani** [comment]
please explain by including error messages and ideally a repository that reproduces the error
