### ISSUE TITLE
cjs module import from example not working since 2.2.0

### ISSUE THREAD

**Issue by J12934** [niieani/hashids.js#207]
Hi 👋
Over at https://github.com/bkimminich/juice-shop the application startup stopped working since the 2.2.0 release last night. See issue https://github.com/bkimminich/juice-shop/issues/1289

It seems like the cjs import as described in the readme doesn't work correctly anymore.
I created a minimal reproduction repo over here: https://github.com/J12934/hashids-cjs-reproduction

```bash
git clone https://github.com/J12934/hashids-cjs-reproduction
npm install
node index.js
```

Crashes with:

```txt
➜ node index.js
internal/modules/cjs/loader.js:532
  throw e;
  ^

Error: Package exports for '/private/tmp/test/node_modules/hashids' do not define a './cjs/index.js' subpath
    at applyExports (internal/modules/cjs/loader.js:529:13)
    at resolveExports (internal/modules/cjs/loader.js:549:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:664:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/private/tmp/test/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10) {
  code: 'MODULE_NOT_FOUND'
}
```

Pinning hashids version to 2.1.0 fixes this issue for now.
Did anything change to the cjs module? Do we need to import / requrie it differently now?

**Comment by niieani** [comment]
Sorry about this @J12934, can you try hashids 2.1.1? I think this issue only presented itself when requiring `hashids/cjs/index` specifically. If you required `hashids/cjs` I believe it had worked.

Anyway, I've relaxed the specificity, so all variations should work now (also added at test for this).

**Comment by frxnz** [comment]
@niieani I'm having this issue as well, specifically when required `hashids/cjs`

With 2.1.1 I get the same issue as you can see in the REPL:

```bash
~/git/strangeluv 14s
❯ npm i hashids@latest 
+ hashids@2.2.1
added 1 package from 3 contributors and audited 919284 packages in 17.168s

44 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


~/git/strangeluv 20s
❯ node
Welcome to Node.js v13.2.0.
Type ".help" for more information.
> const hashids = require('hashids/cjs')
Thrown:
Error: Package exports for '/Users/derek/git/strangeluv/node_modules/hashids' do not define a valid './cjs' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:607:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18) {
  code: 'MODULE_NOT_FOUND'
}
> 
```

**Comment by J12934** [comment]
2.2.1 is working for me 👍

Weirdly I'm getting the `(node:46377) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time` warning when running on node 13 (`v13.7.0`).
On node 12 (`v12.14.1`) this doesn't show at all, but just works normally without the warning.

Anyway thank you for the swift response, much appreciated 👍👏

**Comment by Undistraction** [comment]
Seeing a variation of this intermittently in 2.2.8 using yarn:
> Module not found: Error: Package path ./cjs is not exported from package /Users/me/Sites/app/node_modules/hashids (see exports field in 
/Users/me/Sites/app/node_modules/hashids/package.json)

 Verified that there is only one version using `yarn why hashids`, and verified that there is an `index.js` file in `/Users/me/Sites/app/node_modules/hashids/cjs`, but still see this error when compiling sometimes.
