### ISSUE TITLE
Improve documentation about how to import in Typescript+Node<13.11

### ISSUE THREAD

**Issue by peps** [niieani/hashids.js#210]
Hi,  im trying to use Hashids with Typescript and Node.

`import Hashids from 'hashids';` 

I'm not getting any Typescript errors in the editor, but Im getting this error when the code is compiled. 

`Using ts-node version 8.5.4, typescript version 3.7.5`

`Error: No valid exports main found for 'node_modules\hashids'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (encodeID.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
[ERROR] 18:03:43 Error: No valid exports main found for 'node_modules\hashids'`

Thanks!

**Comment by oleg-koval** [comment]
@peps have the same issue,

Temporarily fixed with:

```typescript
declare let require: any;
const Hashids = require('hashids/cjs');
```

Would be good to have an update on this

**Comment by enahomurphy** [comment]
this works for me `import  hashids from 'hashids/cjs'`

**Comment by niieani** [comment]
See README: https://github.com/niieani/hashids.js#use-in-commonjs-environments-most-often-nodejs
You need to require or import a different file depending on the environment, just like @enahomurphy suggested. One exception is if you use Node 13.11, it also will work out of the box from the main import in the upcoming Node 14 LTS.
