### ISSUE TITLE
node_modules/hashids' do not define a valid './cjs' target

### ISSUE THREAD

**Issue by hiraditya** [niieani/hashids.js#273]
It is working on my local machine with 
npm -v: 6.14.4
node -v: v14.0.0

but on the server with:
npm -v: 6.13.6
node -v: v13.6.0

I get the following error:
```
> export NODE_ENV=production; node start.js

internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: Package exports for '/dataweb/node_modules/hashids' do not define a valid './cjs' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:621:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/dataweb/models/solution.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/dataweb/routes/pastebinRoute.js:2:18) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codeeditor@1.0.0 prod: `export NODE_ENV=production; node start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codeeditor@1.0.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by niieani** [comment]
Please use the latest version of hashids, or node LTS - v12 or v14.
